### ISSUE TITLE
Check not work after update to activemq 5.15.12

### ISSUE THREAD

**Issue by koraz0815** [KevinHonka/check_activeMQ#8]
**Describe the bug**
After Update from activemq to 5.15.12 the check not work

**To Reproduce**
Update activemq from 5.15.11 to 5.15.12

**Check Output**
`# /usr/lib64/nagios/plugins/check_activemq health
Traceback (most recent call last):
  File "/usr/lib64/nagios/plugins/check_activemq", line 320, in <module>
    check.get_health_status(args.broker)
  File "/usr/lib64/nagios/plugins/check_activemq", line 130, in get_health_status
    "Uptime": data['value']['Uptime'],
KeyError: 'value'
`
**Desktop:**
 - OS: centOS7
 - Browser firefox
- Check-Version: 1.0

**Additional context**
The cause of the problem is an update from jolokia.
wit curl i can use the option `-H "Origin: http://localhost:8161"` to access jolokia api.

**Comment by bodsch** [comment]
maybe fixed with PR #7 ?

**Comment by uv-jfuchs** [comment]
I try this Version but i get the following error:
`
File "/usr/lib64/nagios/plugins/check_activemq", line 18
"""
      ^
TabError: inconsistent use of tabs and spaces in indentation`

**Comment by koraz0815** [comment]
No sorry.
After update to activemq 5.15.12 I still get no data with this check.
Before update
`vagrant@activemq.XXX:~$ /usr/lib64/nagios/plugins/check_activemq --host localhost --port 8161 --check health
Apache-MQ - OK
  Uptime: 29.709 seconds 
  BrokerVersion: 5.15.11 
  Store Usage in %: 0 
  Memory Usage in %: 0 
  Total Connections: 0 
  Total Dequeue Count: 0 
  Total Enqueue Count: 5 
`
After Update:
`vagrant@activemq.XXX:~$ /usr/lib64/nagios/plugins/check_activemq --check health                                                                                                                                                                                              
vagrant@activemq.XXX:~$`

**Comment by bodsch** [comment]
Which version did you use before the upgrade?
And which version of the check do you currently use?
That would also be helpful to know.

**Comment by koraz0815** [comment]
Hi,
I use activemq 5.15.11 before update to 5.15.12.
For the check I use the newest version from the master-branch of this check

**Comment by bodsch** [comment]
I can confirm that the check no longer works with AMQ version 5.15.12.
With versions 5.15. [6-11] however, it worked fine. 

maybe ist that the reason:
https://github.com/apache/activemq/pull/496/files

and here:
http://mail-archives.apache.org/mod_mbox/activemq-users/202003.mbox/%3c2A47766F-A184-4B33-B330-51F3EFA4DFE2@nanthrax.net%3e

**Comment by bodsch** [comment]
This is not a bug in the check, but an extended security configuration of AMQ.
Please configure AMQ accordingly.

A feedback would help us.

**Comment by KevinHonka** [comment]
as @bodsch said this seems to be due to a security improvement in AMQ. For now you have to configure it correctly to let the check do its thing.
